// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WebSocketFrame_FrameType int32

const (
	WebSocketFrame_CONNECT WebSocketFrame_FrameType = 0 // 连接建立，携带元信息（仅第一帧）
	WebSocketFrame_TEXT    WebSocketFrame_FrameType = 1 // 文本消息
	WebSocketFrame_BINARY  WebSocketFrame_FrameType = 2 // 二进制消息
	WebSocketFrame_CLOSE   WebSocketFrame_FrameType = 3 // 关闭连接
	WebSocketFrame_RESULT  WebSocketFrame_FrameType = 4 // 连接结束，携带 ForwardResult
)

// Enum value maps for WebSocketFrame_FrameType.
var (
	WebSocketFrame_FrameType_name = map[int32]string{
		0: "CONNECT",
		1: "TEXT",
		2: "BINARY",
		3: "CLOSE",
		4: "RESULT",
	}
	WebSocketFrame_FrameType_value = map[string]int32{
		"CONNECT": 0,
		"TEXT":    1,
		"BINARY":  2,
		"CLOSE":   3,
		"RESULT":  4,
	}
)

func (x WebSocketFrame_FrameType) Enum() *WebSocketFrame_FrameType {
	p := new(WebSocketFrame_FrameType)
	*p = x
	return p
}

func (x WebSocketFrame_FrameType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebSocketFrame_FrameType) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[0].Descriptor()
}

func (WebSocketFrame_FrameType) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[0]
}

func (x WebSocketFrame_FrameType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebSocketFrame_FrameType.Descriptor instead.
func (WebSocketFrame_FrameType) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{23, 0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

type StringResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringResponse) Reset() {
	*x = StringResponse{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringResponse) ProtoMessage() {}

func (x *StringResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringResponse.ProtoReflect.Descriptor instead.
func (*StringResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *StringResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// HeaderValues 支持同一 Header 有多个值（如 Set-Cookie）
type HeaderValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderValues) Reset() {
	*x = HeaderValues{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderValues) ProtoMessage() {}

func (x *HeaderValues) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderValues.ProtoReflect.Descriptor instead.
func (*HeaderValues) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *HeaderValues) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type PluginInfoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version         string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Description     string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Author          string                 `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	Type            string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	AccountTypes    []*AccountTypeProto    `protobuf:"bytes,7,rep,name=account_types,json=accountTypes,proto3" json:"account_types,omitempty"`
	FrontendPages   []*FrontendPageProto   `protobuf:"bytes,8,rep,name=frontend_pages,json=frontendPages,proto3" json:"frontend_pages,omitempty"`
	FrontendWidgets []*FrontendWidgetProto `protobuf:"bytes,9,rep,name=frontend_widgets,json=frontendWidgets,proto3" json:"frontend_widgets,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PluginInfoResponse) Reset() {
	*x = PluginInfoResponse{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfoResponse) ProtoMessage() {}

func (x *PluginInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfoResponse.ProtoReflect.Descriptor instead.
func (*PluginInfoResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *PluginInfoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInfoResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginInfoResponse) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PluginInfoResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PluginInfoResponse) GetAccountTypes() []*AccountTypeProto {
	if x != nil {
		return x.AccountTypes
	}
	return nil
}

func (x *PluginInfoResponse) GetFrontendPages() []*FrontendPageProto {
	if x != nil {
		return x.FrontendPages
	}
	return nil
}

func (x *PluginInfoResponse) GetFrontendWidgets() []*FrontendWidgetProto {
	if x != nil {
		return x.FrontendWidgets
	}
	return nil
}

type AccountTypeProto struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Key           string                  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Label         string                  `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Description   string                  `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Fields        []*CredentialFieldProto `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountTypeProto) Reset() {
	*x = AccountTypeProto{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountTypeProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountTypeProto) ProtoMessage() {}

func (x *AccountTypeProto) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountTypeProto.ProtoReflect.Descriptor instead.
func (*AccountTypeProto) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *AccountTypeProto) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AccountTypeProto) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AccountTypeProto) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AccountTypeProto) GetFields() []*CredentialFieldProto {
	if x != nil {
		return x.Fields
	}
	return nil
}

type CredentialFieldProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Required      bool                   `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	Placeholder   string                 `protobuf:"bytes,5,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialFieldProto) Reset() {
	*x = CredentialFieldProto{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialFieldProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialFieldProto) ProtoMessage() {}

func (x *CredentialFieldProto) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialFieldProto.ProtoReflect.Descriptor instead.
func (*CredentialFieldProto) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *CredentialFieldProto) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CredentialFieldProto) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *CredentialFieldProto) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CredentialFieldProto) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *CredentialFieldProto) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

type FrontendPageProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrontendPageProto) Reset() {
	*x = FrontendPageProto{}
	mi := &file_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrontendPageProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrontendPageProto) ProtoMessage() {}

func (x *FrontendPageProto) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrontendPageProto.ProtoReflect.Descriptor instead.
func (*FrontendPageProto) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *FrontendPageProto) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FrontendPageProto) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FrontendPageProto) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *FrontendPageProto) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type FrontendWidgetProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          string                 `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`
	EntryFile     string                 `protobuf:"bytes,2,opt,name=entry_file,json=entryFile,proto3" json:"entry_file,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrontendWidgetProto) Reset() {
	*x = FrontendWidgetProto{}
	mi := &file_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrontendWidgetProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrontendWidgetProto) ProtoMessage() {}

func (x *FrontendWidgetProto) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrontendWidgetProto.ProtoReflect.Descriptor instead.
func (*FrontendWidgetProto) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *FrontendWidgetProto) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

func (x *FrontendWidgetProto) GetEntryFile() string {
	if x != nil {
		return x.EntryFile
	}
	return ""
}

func (x *FrontendWidgetProto) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        map[string]string      `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LogLevel      string                 `protobuf:"bytes,2,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *InitRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *InitRequest) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

type ModelInfoProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,3,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	InputPrice    float64                `protobuf:"fixed64,4,opt,name=input_price,json=inputPrice,proto3" json:"input_price,omitempty"`
	OutputPrice   float64                `protobuf:"fixed64,5,opt,name=output_price,json=outputPrice,proto3" json:"output_price,omitempty"`
	CachePrice    float64                `protobuf:"fixed64,6,opt,name=cache_price,json=cachePrice,proto3" json:"cache_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelInfoProto) Reset() {
	*x = ModelInfoProto{}
	mi := &file_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfoProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfoProto) ProtoMessage() {}

func (x *ModelInfoProto) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfoProto.ProtoReflect.Descriptor instead.
func (*ModelInfoProto) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *ModelInfoProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModelInfoProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelInfoProto) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *ModelInfoProto) GetInputPrice() float64 {
	if x != nil {
		return x.InputPrice
	}
	return 0
}

func (x *ModelInfoProto) GetOutputPrice() float64 {
	if x != nil {
		return x.OutputPrice
	}
	return 0
}

func (x *ModelInfoProto) GetCachePrice() float64 {
	if x != nil {
		return x.CachePrice
	}
	return 0
}

type ModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*ModelInfoProto      `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelsResponse) Reset() {
	*x = ModelsResponse{}
	mi := &file_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelsResponse) ProtoMessage() {}

func (x *ModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelsResponse.ProtoReflect.Descriptor instead.
func (*ModelsResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *ModelsResponse) GetModels() []*ModelInfoProto {
	if x != nil {
		return x.Models
	}
	return nil
}

type RouteDefinitionProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteDefinitionProto) Reset() {
	*x = RouteDefinitionProto{}
	mi := &file_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteDefinitionProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteDefinitionProto) ProtoMessage() {}

func (x *RouteDefinitionProto) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteDefinitionProto.ProtoReflect.Descriptor instead.
func (*RouteDefinitionProto) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *RouteDefinitionProto) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RouteDefinitionProto) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RouteDefinitionProto) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type RoutesResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Routes        []*RouteDefinitionProto `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutesResponse) Reset() {
	*x = RoutesResponse{}
	mi := &file_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutesResponse) ProtoMessage() {}

func (x *RoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutesResponse.ProtoReflect.Descriptor instead.
func (*RoutesResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *RoutesResponse) GetRoutes() []*RouteDefinitionProto {
	if x != nil {
		return x.Routes
	}
	return nil
}

type ForwardRequest struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	AccountId       int64                    `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccountName     string                   `protobuf:"bytes,2,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	AccountPlatform string                   `protobuf:"bytes,3,opt,name=account_platform,json=accountPlatform,proto3" json:"account_platform,omitempty"`
	AccountType     string                   `protobuf:"bytes,4,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	CredentialsJson []byte                   `protobuf:"bytes,5,opt,name=credentials_json,json=credentialsJson,proto3" json:"credentials_json,omitempty"`
	ProxyUrl        string                   `protobuf:"bytes,6,opt,name=proxy_url,json=proxyUrl,proto3" json:"proxy_url,omitempty"`
	Body            []byte                   `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	Headers         map[string]*HeaderValues `protobuf:"bytes,8,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Model           string                   `protobuf:"bytes,9,opt,name=model,proto3" json:"model,omitempty"`
	Stream          bool                     `protobuf:"varint,10,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ForwardRequest) Reset() {
	*x = ForwardRequest{}
	mi := &file_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardRequest) ProtoMessage() {}

func (x *ForwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardRequest.ProtoReflect.Descriptor instead.
func (*ForwardRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *ForwardRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *ForwardRequest) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *ForwardRequest) GetAccountPlatform() string {
	if x != nil {
		return x.AccountPlatform
	}
	return ""
}

func (x *ForwardRequest) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *ForwardRequest) GetCredentialsJson() []byte {
	if x != nil {
		return x.CredentialsJson
	}
	return nil
}

func (x *ForwardRequest) GetProxyUrl() string {
	if x != nil {
		return x.ProxyUrl
	}
	return ""
}

func (x *ForwardRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ForwardRequest) GetHeaders() map[string]*HeaderValues {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ForwardRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ForwardRequest) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

type ForwardResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	InputTokens   int32                  `protobuf:"varint,2,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens  int32                  `protobuf:"varint,3,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	CacheTokens   int32                  `protobuf:"varint,4,opt,name=cache_tokens,json=cacheTokens,proto3" json:"cache_tokens,omitempty"`
	Model         string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	DurationMs    int64                  `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	AccountStatus string                 `protobuf:"bytes,7,opt,name=account_status,json=accountStatus,proto3" json:"account_status,omitempty"` // "" / "rate_limited" / "disabled" / "expired"
	RetryAfterMs  int64                  `protobuf:"varint,8,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"` // 限流时建议等待时间（毫秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardResult) Reset() {
	*x = ForwardResult{}
	mi := &file_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardResult) ProtoMessage() {}

func (x *ForwardResult) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardResult.ProtoReflect.Descriptor instead.
func (*ForwardResult) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *ForwardResult) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ForwardResult) GetInputTokens() int32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *ForwardResult) GetOutputTokens() int32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *ForwardResult) GetCacheTokens() int32 {
	if x != nil {
		return x.CacheTokens
	}
	return 0
}

func (x *ForwardResult) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ForwardResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ForwardResult) GetAccountStatus() string {
	if x != nil {
		return x.AccountStatus
	}
	return ""
}

func (x *ForwardResult) GetRetryAfterMs() int64 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

type ForwardChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Done          bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	FinalResult   *ForwardResult         `protobuf:"bytes,3,opt,name=final_result,json=finalResult,proto3" json:"final_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardChunk) Reset() {
	*x = ForwardChunk{}
	mi := &file_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardChunk) ProtoMessage() {}

func (x *ForwardChunk) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardChunk.ProtoReflect.Descriptor instead.
func (*ForwardChunk) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *ForwardChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ForwardChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *ForwardChunk) GetFinalResult() *ForwardResult {
	if x != nil {
		return x.FinalResult
	}
	return nil
}

type CredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credentials   map[string]string      `protobuf:"bytes,1,rep,name=credentials,proto3" json:"credentials,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialsRequest) Reset() {
	*x = CredentialsRequest{}
	mi := &file_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialsRequest) ProtoMessage() {}

func (x *CredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialsRequest.ProtoReflect.Descriptor instead.
func (*CredentialsRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *CredentialsRequest) GetCredentials() map[string]string {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type QuotaInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         float64                `protobuf:"fixed64,1,opt,name=total,proto3" json:"total,omitempty"`
	Used          float64                `protobuf:"fixed64,2,opt,name=used,proto3" json:"used,omitempty"`
	Remaining     float64                `protobuf:"fixed64,3,opt,name=remaining,proto3" json:"remaining,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Extra         map[string]string      `protobuf:"bytes,6,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuotaInfoResponse) Reset() {
	*x = QuotaInfoResponse{}
	mi := &file_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuotaInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaInfoResponse) ProtoMessage() {}

func (x *QuotaInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaInfoResponse.ProtoReflect.Descriptor instead.
func (*QuotaInfoResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *QuotaInfoResponse) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *QuotaInfoResponse) GetUsed() float64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *QuotaInfoResponse) GetRemaining() float64 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *QuotaInfoResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *QuotaInfoResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *QuotaInfoResponse) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

type HttpRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Method        string                   `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Query         string                   `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	Headers       map[string]*HeaderValues `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                   `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	RemoteAddr    string                   `protobuf:"bytes,6,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpRequest) Reset() {
	*x = HttpRequest{}
	mi := &file_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRequest) ProtoMessage() {}

func (x *HttpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRequest.ProtoReflect.Descriptor instead.
func (*HttpRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *HttpRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HttpRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *HttpRequest) GetHeaders() map[string]*HeaderValues {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HttpRequest) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

type HttpResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	StatusCode    int32                    `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers       map[string]*HeaderValues `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpResponse) Reset() {
	*x = HttpResponse{}
	mi := &file_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpResponse) ProtoMessage() {}

func (x *HttpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpResponse.ProtoReflect.Descriptor instead.
func (*HttpResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *HttpResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *HttpResponse) GetHeaders() map[string]*HeaderValues {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type HttpResponseChunk struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Data          []byte                   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Done          bool                     `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	StatusCode    int32                    `protobuf:"varint,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers       map[string]*HeaderValues `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpResponseChunk) Reset() {
	*x = HttpResponseChunk{}
	mi := &file_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpResponseChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpResponseChunk) ProtoMessage() {}

func (x *HttpResponseChunk) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpResponseChunk.ProtoReflect.Descriptor instead.
func (*HttpResponseChunk) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *HttpResponseChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *HttpResponseChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *HttpResponseChunk) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *HttpResponseChunk) GetHeaders() map[string]*HeaderValues {
	if x != nil {
		return x.Headers
	}
	return nil
}

type BackgroundTaskProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IntervalMs    int64                  `protobuf:"varint,2,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackgroundTaskProto) Reset() {
	*x = BackgroundTaskProto{}
	mi := &file_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackgroundTaskProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackgroundTaskProto) ProtoMessage() {}

func (x *BackgroundTaskProto) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackgroundTaskProto.ProtoReflect.Descriptor instead.
func (*BackgroundTaskProto) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{21}
}

func (x *BackgroundTaskProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackgroundTaskProto) GetIntervalMs() int64 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

type BackgroundTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*BackgroundTaskProto `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackgroundTasksResponse) Reset() {
	*x = BackgroundTasksResponse{}
	mi := &file_plugin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackgroundTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackgroundTasksResponse) ProtoMessage() {}

func (x *BackgroundTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackgroundTasksResponse.ProtoReflect.Descriptor instead.
func (*BackgroundTasksResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{22}
}

func (x *BackgroundTasksResponse) GetTasks() []*BackgroundTaskProto {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type WebSocketFrame struct {
	state protoimpl.MessageState   `protogen:"open.v1"`
	Type  WebSocketFrame_FrameType `protobuf:"varint,1,opt,name=type,proto3,enum=airgate.plugin.v1.WebSocketFrame_FrameType" json:"type,omitempty"`
	Data  []byte                   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// 仅 CONNECT 帧使用
	ConnectInfo *WebSocketConnectInfo `protobuf:"bytes,3,opt,name=connect_info,json=connectInfo,proto3" json:"connect_info,omitempty"`
	// 仅 CLOSE 帧使用
	CloseCode   int32  `protobuf:"varint,4,opt,name=close_code,json=closeCode,proto3" json:"close_code,omitempty"`
	CloseReason string `protobuf:"bytes,5,opt,name=close_reason,json=closeReason,proto3" json:"close_reason,omitempty"`
	// 仅 RESULT 帧使用
	Result        *ForwardResult `protobuf:"bytes,6,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketFrame) Reset() {
	*x = WebSocketFrame{}
	mi := &file_plugin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketFrame) ProtoMessage() {}

func (x *WebSocketFrame) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketFrame.ProtoReflect.Descriptor instead.
func (*WebSocketFrame) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{23}
}

func (x *WebSocketFrame) GetType() WebSocketFrame_FrameType {
	if x != nil {
		return x.Type
	}
	return WebSocketFrame_CONNECT
}

func (x *WebSocketFrame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WebSocketFrame) GetConnectInfo() *WebSocketConnectInfo {
	if x != nil {
		return x.ConnectInfo
	}
	return nil
}

func (x *WebSocketFrame) GetCloseCode() int32 {
	if x != nil {
		return x.CloseCode
	}
	return 0
}

func (x *WebSocketFrame) GetCloseReason() string {
	if x != nil {
		return x.CloseReason
	}
	return ""
}

func (x *WebSocketFrame) GetResult() *ForwardResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type WebSocketConnectInfo struct {
	state        protoimpl.MessageState   `protogen:"open.v1"`
	Path         string                   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Query        string                   `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Headers      map[string]*HeaderValues `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RemoteAddr   string                   `protobuf:"bytes,4,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	ConnectionId string                   `protobuf:"bytes,5,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// 核心已调度的账户信息
	AccountId       int64  `protobuf:"varint,6,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccountName     string `protobuf:"bytes,7,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	AccountPlatform string `protobuf:"bytes,8,opt,name=account_platform,json=accountPlatform,proto3" json:"account_platform,omitempty"`
	AccountType     string `protobuf:"bytes,9,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	CredentialsJson []byte `protobuf:"bytes,10,opt,name=credentials_json,json=credentialsJson,proto3" json:"credentials_json,omitempty"`
	ProxyUrl        string `protobuf:"bytes,11,opt,name=proxy_url,json=proxyUrl,proto3" json:"proxy_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WebSocketConnectInfo) Reset() {
	*x = WebSocketConnectInfo{}
	mi := &file_plugin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketConnectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketConnectInfo) ProtoMessage() {}

func (x *WebSocketConnectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketConnectInfo.ProtoReflect.Descriptor instead.
func (*WebSocketConnectInfo) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{24}
}

func (x *WebSocketConnectInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WebSocketConnectInfo) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *WebSocketConnectInfo) GetHeaders() map[string]*HeaderValues {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *WebSocketConnectInfo) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *WebSocketConnectInfo) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *WebSocketConnectInfo) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *WebSocketConnectInfo) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *WebSocketConnectInfo) GetAccountPlatform() string {
	if x != nil {
		return x.AccountPlatform
	}
	return ""
}

func (x *WebSocketConnectInfo) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *WebSocketConnectInfo) GetCredentialsJson() []byte {
	if x != nil {
		return x.CredentialsJson
	}
	return nil
}

func (x *WebSocketConnectInfo) GetProxyUrl() string {
	if x != nil {
		return x.ProxyUrl
	}
	return ""
}

type WebAssetFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebAssetFile) Reset() {
	*x = WebAssetFile{}
	mi := &file_plugin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebAssetFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebAssetFile) ProtoMessage() {}

func (x *WebAssetFile) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebAssetFile.ProtoReflect.Descriptor instead.
func (*WebAssetFile) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{25}
}

func (x *WebAssetFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WebAssetFile) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type WebAssetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*WebAssetFile        `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	HasAssets     bool                   `protobuf:"varint,2,opt,name=has_assets,json=hasAssets,proto3" json:"has_assets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebAssetsResponse) Reset() {
	*x = WebAssetsResponse{}
	mi := &file_plugin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebAssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebAssetsResponse) ProtoMessage() {}

func (x *WebAssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebAssetsResponse.ProtoReflect.Descriptor instead.
func (*WebAssetsResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{26}
}

func (x *WebAssetsResponse) GetFiles() []*WebAssetFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *WebAssetsResponse) GetHasAssets() bool {
	if x != nil {
		return x.HasAssets
	}
	return false
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\x11airgate.plugin.v1\"\a\n" +
	"\x05Empty\"&\n" +
	"\x0eStringResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"&\n" +
	"\fHeaderValues\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\x8a\x03\n" +
	"\x12PluginInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06author\x18\x05 \x01(\tR\x06author\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12H\n" +
	"\raccount_types\x18\a \x03(\v2#.airgate.plugin.v1.AccountTypeProtoR\faccountTypes\x12K\n" +
	"\x0efrontend_pages\x18\b \x03(\v2$.airgate.plugin.v1.FrontendPageProtoR\rfrontendPages\x12Q\n" +
	"\x10frontend_widgets\x18\t \x03(\v2&.airgate.plugin.v1.FrontendWidgetProtoR\x0ffrontendWidgets\"\x9d\x01\n" +
	"\x10AccountTypeProto\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12?\n" +
	"\x06fields\x18\x04 \x03(\v2'.airgate.plugin.v1.CredentialFieldProtoR\x06fields\"\x90\x01\n" +
	"\x14CredentialFieldProto\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\x12 \n" +
	"\vplaceholder\x18\x05 \x01(\tR\vplaceholder\"s\n" +
	"\x11FrontendPageProto\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"^\n" +
	"\x13FrontendWidgetProto\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\tR\x04slot\x12\x1d\n" +
	"\n" +
	"entry_file\x18\x02 \x01(\tR\tentryFile\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\"\xa9\x01\n" +
	"\vInitRequest\x12B\n" +
	"\x06config\x18\x01 \x03(\v2*.airgate.plugin.v1.InitRequest.ConfigEntryR\x06config\x12\x1b\n" +
	"\tlog_level\x18\x02 \x01(\tR\blogLevel\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb8\x01\n" +
	"\x0eModelInfoProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x03 \x01(\x05R\tmaxTokens\x12\x1f\n" +
	"\vinput_price\x18\x04 \x01(\x01R\n" +
	"inputPrice\x12!\n" +
	"\foutput_price\x18\x05 \x01(\x01R\voutputPrice\x12\x1f\n" +
	"\vcache_price\x18\x06 \x01(\x01R\n" +
	"cachePrice\"K\n" +
	"\x0eModelsResponse\x129\n" +
	"\x06models\x18\x01 \x03(\v2!.airgate.plugin.v1.ModelInfoProtoR\x06models\"d\n" +
	"\x14RouteDefinitionProto\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"Q\n" +
	"\x0eRoutesResponse\x12?\n" +
	"\x06routes\x18\x01 \x03(\v2'.airgate.plugin.v1.RouteDefinitionProtoR\x06routes\"\xd1\x03\n" +
	"\x0eForwardRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12!\n" +
	"\faccount_name\x18\x02 \x01(\tR\vaccountName\x12)\n" +
	"\x10account_platform\x18\x03 \x01(\tR\x0faccountPlatform\x12!\n" +
	"\faccount_type\x18\x04 \x01(\tR\vaccountType\x12)\n" +
	"\x10credentials_json\x18\x05 \x01(\fR\x0fcredentialsJson\x12\x1b\n" +
	"\tproxy_url\x18\x06 \x01(\tR\bproxyUrl\x12\x12\n" +
	"\x04body\x18\a \x01(\fR\x04body\x12H\n" +
	"\aheaders\x18\b \x03(\v2..airgate.plugin.v1.ForwardRequest.HeadersEntryR\aheaders\x12\x14\n" +
	"\x05model\x18\t \x01(\tR\x05model\x12\x16\n" +
	"\x06stream\x18\n" +
	" \x01(\bR\x06stream\x1a[\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.airgate.plugin.v1.HeaderValuesR\x05value:\x028\x01\"\x9f\x02\n" +
	"\rForwardResult\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12!\n" +
	"\finput_tokens\x18\x02 \x01(\x05R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x03 \x01(\x05R\foutputTokens\x12!\n" +
	"\fcache_tokens\x18\x04 \x01(\x05R\vcacheTokens\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x03R\n" +
	"durationMs\x12%\n" +
	"\x0eaccount_status\x18\a \x01(\tR\raccountStatus\x12$\n" +
	"\x0eretry_after_ms\x18\b \x01(\x03R\fretryAfterMs\"{\n" +
	"\fForwardChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\x12C\n" +
	"\ffinal_result\x18\x03 \x01(\v2 .airgate.plugin.v1.ForwardResultR\vfinalResult\"\xae\x01\n" +
	"\x12CredentialsRequest\x12X\n" +
	"\vcredentials\x18\x01 \x03(\v26.airgate.plugin.v1.CredentialsRequest.CredentialsEntryR\vcredentials\x1a>\n" +
	"\x10CredentialsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x97\x02\n" +
	"\x11QuotaInfoResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x01R\x05total\x12\x12\n" +
	"\x04used\x18\x02 \x01(\x01R\x04used\x12\x1c\n" +
	"\tremaining\x18\x03 \x01(\x01R\tremaining\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\tR\texpiresAt\x12E\n" +
	"\x05extra\x18\x06 \x03(\v2/.airgate.plugin.v1.QuotaInfoResponse.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa8\x02\n" +
	"\vHttpRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x12E\n" +
	"\aheaders\x18\x04 \x03(\v2+.airgate.plugin.v1.HttpRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x05 \x01(\fR\x04body\x12\x1f\n" +
	"\vremote_addr\x18\x06 \x01(\tR\n" +
	"remoteAddr\x1a[\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.airgate.plugin.v1.HeaderValuesR\x05value:\x028\x01\"\xe8\x01\n" +
	"\fHttpResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12F\n" +
	"\aheaders\x18\x02 \x03(\v2,.airgate.plugin.v1.HttpResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x1a[\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.airgate.plugin.v1.HeaderValuesR\x05value:\x028\x01\"\x86\x02\n" +
	"\x11HttpResponseChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\x12\x1f\n" +
	"\vstatus_code\x18\x03 \x01(\x05R\n" +
	"statusCode\x12K\n" +
	"\aheaders\x18\x04 \x03(\v21.airgate.plugin.v1.HttpResponseChunk.HeadersEntryR\aheaders\x1a[\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.airgate.plugin.v1.HeaderValuesR\x05value:\x028\x01\"J\n" +
	"\x13BackgroundTaskProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vinterval_ms\x18\x02 \x01(\x03R\n" +
	"intervalMs\"W\n" +
	"\x17BackgroundTasksResponse\x12<\n" +
	"\x05tasks\x18\x01 \x03(\v2&.airgate.plugin.v1.BackgroundTaskProtoR\x05tasks\"\xf4\x02\n" +
	"\x0eWebSocketFrame\x12?\n" +
	"\x04type\x18\x01 \x01(\x0e2+.airgate.plugin.v1.WebSocketFrame.FrameTypeR\x04type\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12J\n" +
	"\fconnect_info\x18\x03 \x01(\v2'.airgate.plugin.v1.WebSocketConnectInfoR\vconnectInfo\x12\x1d\n" +
	"\n" +
	"close_code\x18\x04 \x01(\x05R\tcloseCode\x12!\n" +
	"\fclose_reason\x18\x05 \x01(\tR\vcloseReason\x128\n" +
	"\x06result\x18\x06 \x01(\v2 .airgate.plugin.v1.ForwardResultR\x06result\"E\n" +
	"\tFrameType\x12\v\n" +
	"\aCONNECT\x10\x00\x12\b\n" +
	"\x04TEXT\x10\x01\x12\n" +
	"\n" +
	"\x06BINARY\x10\x02\x12\t\n" +
	"\x05CLOSE\x10\x03\x12\n" +
	"\n" +
	"\x06RESULT\x10\x04\"\x8b\x04\n" +
	"\x14WebSocketConnectInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12N\n" +
	"\aheaders\x18\x03 \x03(\v24.airgate.plugin.v1.WebSocketConnectInfo.HeadersEntryR\aheaders\x12\x1f\n" +
	"\vremote_addr\x18\x04 \x01(\tR\n" +
	"remoteAddr\x12#\n" +
	"\rconnection_id\x18\x05 \x01(\tR\fconnectionId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x06 \x01(\x03R\taccountId\x12!\n" +
	"\faccount_name\x18\a \x01(\tR\vaccountName\x12)\n" +
	"\x10account_platform\x18\b \x01(\tR\x0faccountPlatform\x12!\n" +
	"\faccount_type\x18\t \x01(\tR\vaccountType\x12)\n" +
	"\x10credentials_json\x18\n" +
	" \x01(\fR\x0fcredentialsJson\x12\x1b\n" +
	"\tproxy_url\x18\v \x01(\tR\bproxyUrl\x1a[\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.airgate.plugin.v1.HeaderValuesR\x05value:\x028\x01\"<\n" +
	"\fWebAssetFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"i\n" +
	"\x11WebAssetsResponse\x125\n" +
	"\x05files\x18\x01 \x03(\v2\x1f.airgate.plugin.v1.WebAssetFileR\x05files\x12\x1d\n" +
	"\n" +
	"has_assets\x18\x02 \x01(\bR\thasAssets2\xe6\x02\n" +
	"\rPluginService\x12J\n" +
	"\aGetInfo\x12\x18.airgate.plugin.v1.Empty\x1a%.airgate.plugin.v1.PluginInfoResponse\x12@\n" +
	"\x04Init\x12\x1e.airgate.plugin.v1.InitRequest\x1a\x18.airgate.plugin.v1.Empty\x12;\n" +
	"\x05Start\x12\x18.airgate.plugin.v1.Empty\x1a\x18.airgate.plugin.v1.Empty\x12:\n" +
	"\x04Stop\x12\x18.airgate.plugin.v1.Empty\x1a\x18.airgate.plugin.v1.Empty\x12N\n" +
	"\fGetWebAssets\x12\x18.airgate.plugin.v1.Empty\x1a$.airgate.plugin.v1.WebAssetsResponse2\xa3\x05\n" +
	"\x0eGatewayService\x12J\n" +
	"\vGetPlatform\x12\x18.airgate.plugin.v1.Empty\x1a!.airgate.plugin.v1.StringResponse\x12H\n" +
	"\tGetModels\x12\x18.airgate.plugin.v1.Empty\x1a!.airgate.plugin.v1.ModelsResponse\x12H\n" +
	"\tGetRoutes\x12\x18.airgate.plugin.v1.Empty\x1a!.airgate.plugin.v1.RoutesResponse\x12N\n" +
	"\aForward\x12!.airgate.plugin.v1.ForwardRequest\x1a .airgate.plugin.v1.ForwardResult\x12U\n" +
	"\rForwardStream\x12!.airgate.plugin.v1.ForwardRequest\x1a\x1f.airgate.plugin.v1.ForwardChunk0\x01\x12R\n" +
	"\x0fValidateAccount\x12%.airgate.plugin.v1.CredentialsRequest\x1a\x18.airgate.plugin.v1.Empty\x12Y\n" +
	"\n" +
	"QueryQuota\x12%.airgate.plugin.v1.CredentialsRequest\x1a$.airgate.plugin.v1.QuotaInfoResponse\x12[\n" +
	"\x0fHandleWebSocket\x12!.airgate.plugin.v1.WebSocketFrame\x1a!.airgate.plugin.v1.WebSocketFrame(\x010\x012\xde\x02\n" +
	"\x10ExtensionService\x12=\n" +
	"\aMigrate\x12\x18.airgate.plugin.v1.Empty\x1a\x18.airgate.plugin.v1.Empty\x12Z\n" +
	"\x12GetBackgroundTasks\x12\x18.airgate.plugin.v1.Empty\x1a*.airgate.plugin.v1.BackgroundTasksResponse\x12P\n" +
	"\rHandleRequest\x12\x1e.airgate.plugin.v1.HttpRequest\x1a\x1f.airgate.plugin.v1.HttpResponse\x12]\n" +
	"\x13HandleStreamRequest\x12\x1e.airgate.plugin.v1.HttpRequest\x1a$.airgate.plugin.v1.HttpResponseChunk0\x01B+Z)github.com/DouDOU-start/airgate-sdk/protob\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_plugin_proto_goTypes = []any{
	(WebSocketFrame_FrameType)(0),   // 0: airgate.plugin.v1.WebSocketFrame.FrameType
	(*Empty)(nil),                   // 1: airgate.plugin.v1.Empty
	(*StringResponse)(nil),          // 2: airgate.plugin.v1.StringResponse
	(*HeaderValues)(nil),            // 3: airgate.plugin.v1.HeaderValues
	(*PluginInfoResponse)(nil),      // 4: airgate.plugin.v1.PluginInfoResponse
	(*AccountTypeProto)(nil),        // 5: airgate.plugin.v1.AccountTypeProto
	(*CredentialFieldProto)(nil),    // 6: airgate.plugin.v1.CredentialFieldProto
	(*FrontendPageProto)(nil),       // 7: airgate.plugin.v1.FrontendPageProto
	(*FrontendWidgetProto)(nil),     // 8: airgate.plugin.v1.FrontendWidgetProto
	(*InitRequest)(nil),             // 9: airgate.plugin.v1.InitRequest
	(*ModelInfoProto)(nil),          // 10: airgate.plugin.v1.ModelInfoProto
	(*ModelsResponse)(nil),          // 11: airgate.plugin.v1.ModelsResponse
	(*RouteDefinitionProto)(nil),    // 12: airgate.plugin.v1.RouteDefinitionProto
	(*RoutesResponse)(nil),          // 13: airgate.plugin.v1.RoutesResponse
	(*ForwardRequest)(nil),          // 14: airgate.plugin.v1.ForwardRequest
	(*ForwardResult)(nil),           // 15: airgate.plugin.v1.ForwardResult
	(*ForwardChunk)(nil),            // 16: airgate.plugin.v1.ForwardChunk
	(*CredentialsRequest)(nil),      // 17: airgate.plugin.v1.CredentialsRequest
	(*QuotaInfoResponse)(nil),       // 18: airgate.plugin.v1.QuotaInfoResponse
	(*HttpRequest)(nil),             // 19: airgate.plugin.v1.HttpRequest
	(*HttpResponse)(nil),            // 20: airgate.plugin.v1.HttpResponse
	(*HttpResponseChunk)(nil),       // 21: airgate.plugin.v1.HttpResponseChunk
	(*BackgroundTaskProto)(nil),     // 22: airgate.plugin.v1.BackgroundTaskProto
	(*BackgroundTasksResponse)(nil), // 23: airgate.plugin.v1.BackgroundTasksResponse
	(*WebSocketFrame)(nil),          // 24: airgate.plugin.v1.WebSocketFrame
	(*WebSocketConnectInfo)(nil),    // 25: airgate.plugin.v1.WebSocketConnectInfo
	(*WebAssetFile)(nil),            // 26: airgate.plugin.v1.WebAssetFile
	(*WebAssetsResponse)(nil),       // 27: airgate.plugin.v1.WebAssetsResponse
	nil,                             // 28: airgate.plugin.v1.InitRequest.ConfigEntry
	nil,                             // 29: airgate.plugin.v1.ForwardRequest.HeadersEntry
	nil,                             // 30: airgate.plugin.v1.CredentialsRequest.CredentialsEntry
	nil,                             // 31: airgate.plugin.v1.QuotaInfoResponse.ExtraEntry
	nil,                             // 32: airgate.plugin.v1.HttpRequest.HeadersEntry
	nil,                             // 33: airgate.plugin.v1.HttpResponse.HeadersEntry
	nil,                             // 34: airgate.plugin.v1.HttpResponseChunk.HeadersEntry
	nil,                             // 35: airgate.plugin.v1.WebSocketConnectInfo.HeadersEntry
}
var file_plugin_proto_depIdxs = []int32{
	5,  // 0: airgate.plugin.v1.PluginInfoResponse.account_types:type_name -> airgate.plugin.v1.AccountTypeProto
	7,  // 1: airgate.plugin.v1.PluginInfoResponse.frontend_pages:type_name -> airgate.plugin.v1.FrontendPageProto
	8,  // 2: airgate.plugin.v1.PluginInfoResponse.frontend_widgets:type_name -> airgate.plugin.v1.FrontendWidgetProto
	6,  // 3: airgate.plugin.v1.AccountTypeProto.fields:type_name -> airgate.plugin.v1.CredentialFieldProto
	28, // 4: airgate.plugin.v1.InitRequest.config:type_name -> airgate.plugin.v1.InitRequest.ConfigEntry
	10, // 5: airgate.plugin.v1.ModelsResponse.models:type_name -> airgate.plugin.v1.ModelInfoProto
	12, // 6: airgate.plugin.v1.RoutesResponse.routes:type_name -> airgate.plugin.v1.RouteDefinitionProto
	29, // 7: airgate.plugin.v1.ForwardRequest.headers:type_name -> airgate.plugin.v1.ForwardRequest.HeadersEntry
	15, // 8: airgate.plugin.v1.ForwardChunk.final_result:type_name -> airgate.plugin.v1.ForwardResult
	30, // 9: airgate.plugin.v1.CredentialsRequest.credentials:type_name -> airgate.plugin.v1.CredentialsRequest.CredentialsEntry
	31, // 10: airgate.plugin.v1.QuotaInfoResponse.extra:type_name -> airgate.plugin.v1.QuotaInfoResponse.ExtraEntry
	32, // 11: airgate.plugin.v1.HttpRequest.headers:type_name -> airgate.plugin.v1.HttpRequest.HeadersEntry
	33, // 12: airgate.plugin.v1.HttpResponse.headers:type_name -> airgate.plugin.v1.HttpResponse.HeadersEntry
	34, // 13: airgate.plugin.v1.HttpResponseChunk.headers:type_name -> airgate.plugin.v1.HttpResponseChunk.HeadersEntry
	22, // 14: airgate.plugin.v1.BackgroundTasksResponse.tasks:type_name -> airgate.plugin.v1.BackgroundTaskProto
	0,  // 15: airgate.plugin.v1.WebSocketFrame.type:type_name -> airgate.plugin.v1.WebSocketFrame.FrameType
	25, // 16: airgate.plugin.v1.WebSocketFrame.connect_info:type_name -> airgate.plugin.v1.WebSocketConnectInfo
	15, // 17: airgate.plugin.v1.WebSocketFrame.result:type_name -> airgate.plugin.v1.ForwardResult
	35, // 18: airgate.plugin.v1.WebSocketConnectInfo.headers:type_name -> airgate.plugin.v1.WebSocketConnectInfo.HeadersEntry
	26, // 19: airgate.plugin.v1.WebAssetsResponse.files:type_name -> airgate.plugin.v1.WebAssetFile
	3,  // 20: airgate.plugin.v1.ForwardRequest.HeadersEntry.value:type_name -> airgate.plugin.v1.HeaderValues
	3,  // 21: airgate.plugin.v1.HttpRequest.HeadersEntry.value:type_name -> airgate.plugin.v1.HeaderValues
	3,  // 22: airgate.plugin.v1.HttpResponse.HeadersEntry.value:type_name -> airgate.plugin.v1.HeaderValues
	3,  // 23: airgate.plugin.v1.HttpResponseChunk.HeadersEntry.value:type_name -> airgate.plugin.v1.HeaderValues
	3,  // 24: airgate.plugin.v1.WebSocketConnectInfo.HeadersEntry.value:type_name -> airgate.plugin.v1.HeaderValues
	1,  // 25: airgate.plugin.v1.PluginService.GetInfo:input_type -> airgate.plugin.v1.Empty
	9,  // 26: airgate.plugin.v1.PluginService.Init:input_type -> airgate.plugin.v1.InitRequest
	1,  // 27: airgate.plugin.v1.PluginService.Start:input_type -> airgate.plugin.v1.Empty
	1,  // 28: airgate.plugin.v1.PluginService.Stop:input_type -> airgate.plugin.v1.Empty
	1,  // 29: airgate.plugin.v1.PluginService.GetWebAssets:input_type -> airgate.plugin.v1.Empty
	1,  // 30: airgate.plugin.v1.GatewayService.GetPlatform:input_type -> airgate.plugin.v1.Empty
	1,  // 31: airgate.plugin.v1.GatewayService.GetModels:input_type -> airgate.plugin.v1.Empty
	1,  // 32: airgate.plugin.v1.GatewayService.GetRoutes:input_type -> airgate.plugin.v1.Empty
	14, // 33: airgate.plugin.v1.GatewayService.Forward:input_type -> airgate.plugin.v1.ForwardRequest
	14, // 34: airgate.plugin.v1.GatewayService.ForwardStream:input_type -> airgate.plugin.v1.ForwardRequest
	17, // 35: airgate.plugin.v1.GatewayService.ValidateAccount:input_type -> airgate.plugin.v1.CredentialsRequest
	17, // 36: airgate.plugin.v1.GatewayService.QueryQuota:input_type -> airgate.plugin.v1.CredentialsRequest
	24, // 37: airgate.plugin.v1.GatewayService.HandleWebSocket:input_type -> airgate.plugin.v1.WebSocketFrame
	1,  // 38: airgate.plugin.v1.ExtensionService.Migrate:input_type -> airgate.plugin.v1.Empty
	1,  // 39: airgate.plugin.v1.ExtensionService.GetBackgroundTasks:input_type -> airgate.plugin.v1.Empty
	19, // 40: airgate.plugin.v1.ExtensionService.HandleRequest:input_type -> airgate.plugin.v1.HttpRequest
	19, // 41: airgate.plugin.v1.ExtensionService.HandleStreamRequest:input_type -> airgate.plugin.v1.HttpRequest
	4,  // 42: airgate.plugin.v1.PluginService.GetInfo:output_type -> airgate.plugin.v1.PluginInfoResponse
	1,  // 43: airgate.plugin.v1.PluginService.Init:output_type -> airgate.plugin.v1.Empty
	1,  // 44: airgate.plugin.v1.PluginService.Start:output_type -> airgate.plugin.v1.Empty
	1,  // 45: airgate.plugin.v1.PluginService.Stop:output_type -> airgate.plugin.v1.Empty
	27, // 46: airgate.plugin.v1.PluginService.GetWebAssets:output_type -> airgate.plugin.v1.WebAssetsResponse
	2,  // 47: airgate.plugin.v1.GatewayService.GetPlatform:output_type -> airgate.plugin.v1.StringResponse
	11, // 48: airgate.plugin.v1.GatewayService.GetModels:output_type -> airgate.plugin.v1.ModelsResponse
	13, // 49: airgate.plugin.v1.GatewayService.GetRoutes:output_type -> airgate.plugin.v1.RoutesResponse
	15, // 50: airgate.plugin.v1.GatewayService.Forward:output_type -> airgate.plugin.v1.ForwardResult
	16, // 51: airgate.plugin.v1.GatewayService.ForwardStream:output_type -> airgate.plugin.v1.ForwardChunk
	1,  // 52: airgate.plugin.v1.GatewayService.ValidateAccount:output_type -> airgate.plugin.v1.Empty
	18, // 53: airgate.plugin.v1.GatewayService.QueryQuota:output_type -> airgate.plugin.v1.QuotaInfoResponse
	24, // 54: airgate.plugin.v1.GatewayService.HandleWebSocket:output_type -> airgate.plugin.v1.WebSocketFrame
	1,  // 55: airgate.plugin.v1.ExtensionService.Migrate:output_type -> airgate.plugin.v1.Empty
	23, // 56: airgate.plugin.v1.ExtensionService.GetBackgroundTasks:output_type -> airgate.plugin.v1.BackgroundTasksResponse
	20, // 57: airgate.plugin.v1.ExtensionService.HandleRequest:output_type -> airgate.plugin.v1.HttpResponse
	21, // 58: airgate.plugin.v1.ExtensionService.HandleStreamRequest:output_type -> airgate.plugin.v1.HttpResponseChunk
	42, // [42:59] is the sub-list for method output_type
	25, // [25:42] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		EnumInfos:         file_plugin_proto_enumTypes,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
